### PR TITLE
Closes #6: Simple visualization (without ports)

### LINKED ISSUE #6: Visualization without ports
Visualize the intermediate representation of the processing pipeline as a PNG image with the help of GraphViz tool. The input and output ports are not shown yet.

### PR DESCRIPTION
**Pull request by mkobos**
Unfortunately, there are lots of lines that were changed in this pull request. However, I haven't found a reasonable way to split these changes into smaller chunks that would make it easier to digest it. As a small excuse: half of the number of line additions come from new example XML Oozie workflows copied from IIS project's source.

In order to make the review easier, here's a summary of major changes:
- `vipe/graphviz/converter.py` - contains the main new class responsible for visualization, i.e., it is responsible for converting intermediate format represented by Pipeline class to GraphViz's dot text format.
- `vipe/graphviz/dot_wrapper.py` - contains class that is responsible for translating business-level node objects to concepts of the GraphViz's dot format.
- I added information about importance to all pipeline nodes in YAML files used in tests.

### CODE REVIEW

**Comment by marekhorst** [comment]
I'm on it...

**Comment by mkobos** [comment]
Sweet :)

**Comment by marekhorst** [comment]
I will get back to this PR next week.

**Comment by marekhorst** [comment]
Done, I thought it will be much more painful to get through all those commits but it wasn't.

**Comment by mkobos** [comment]
Great

**Comment by marekhorst** [comment]
LGTM

**Pull request closed without merging**
