### PR TITLE
Close #3: Add testing workflows

### LINKED ISSUE #3: Workflows for tests
We want to test tool’s ability to:
1. interpret Oozie workflow correctly,
2. extract information about data passed between between workflow nodes.

In order to do so, we need a set of various real-life-like Oozie workflows showing different use cases:
- subworkflows (e.g., workflow->subworkflow->subsubworkflow),
- fork, join,
- conditional execution paths,
- various types of nodes that we use: Java (standard and based on IIS’es Process class), MapReduce, Hadoop Streaming, Pig, distcp,
- nodes with multiple outputs (especially MapReduce),
- input and output paths defined through parameters (like in [metadataextraction workflow](https://github.com/openaire/iis/blob/master/iis-workflows/iis-workflows-metadataextraction/src/main/resources/eu/dnetlib/iis/workflows/metadataextraction/oozie_app/workflow.xml)),
  parameters and global definitions in Oozie file,
- IIS’es schema generators and by-passes,
- passing only the output directory parameter to subworkflow as the root directory that will contain many data stores produced by this subworkflow (as this is something that I saw in our workflows some time ago),
- maybe some other workflows showing other peculiarities?

These workflows will be used as a part of tool’s test suite.

### PR DESCRIPTION
**Pull request by mkobos**

### CODE REVIEW

**Comment by mkobos** [comment]
I added the most recent workflows that you sent me in e54a705425d8ca2a731103fad7e23c30d923dfee (the're in `vipe/oozie/test/data` directory). Apart from these workflows, the commit contains YAML files generated from these workflows using `vipe/oozie/test/data/run_oozie2yaml_on_workflows.sh` script.

Now for the workflows: I need workflow definitions that potentially would be executable if appropriate Java jars, Pig scripts etc. were present. Such testing workflows would be close enough to real-life workflows for my current needs. Can you modify the workflows so they are like that? 

For example, in "bypass" workflow the "consumer" ingests metadata that is not produced anywhere earlier in this workflow. This is bad since it will upset the code that analyzes such things that will be implemented in #5.

**Comment by marekhorst** [comment]
> Now for the workflows: I need workflow definitions that potentially would be executable if appropriate Java jars, Pig scripts etc. were present. Such testing workflows would be close enough to real-life workflows for my current needs. Can you modify the workflows so they are like that?

This is what I asked about in https://github.com/openaire/vipe/issues/3#issuecomment-152222681. So they should be kind of executable then. What is the priority of this task?

**Comment by mkobos** [comment]
> This is what I asked about in #3 (comment). So they should be kind of executable then. 

Yeah.

> What is the priority of this task?

If I I could get them today this would be great.

**Comment by marekhorst** [comment]
I've just updated workflows.

**Comment by mkobos** [comment]
- In `conditional`, `fs`, `distcp`, and `pig` examples you use a `Finalizer` class in the final node. It doesn't ingest any data so the data flow analysis won't show much. Is it possible to add some real data processing to these examples (so e.g., `fs` action produces some data that is then ingested by a consumer)? This is certainly possible for the `pig` example, but I'm not sure if for the rest of them it would be a "realistic" case.
- Can you add a new `fork` example (`fork2`?) with a single consumer that ingests document and person data stores?

**Comment by marekhorst** [comment]
OK, I am getting back to this issue.

**Comment by marekhorst** [comment]
> In conditional, fs, distcp, and pig examples you use a Finalizer class in the final node. It doesn't ingest any data so the data flow analysis won't show much. Is it possible to add some real data processing to these examples (so e.g., fs action produces some data that is then ingested by a consumer)? This is certainly possible for the pig example, but I'm not sure if for the rest of them it would be a "realistic" case.

I've slightly improved `fs` and `pig` workflows. Yaml files should be regenerated then.

Anyways, shouldn't we keep those workflows compact (now I am thinking of `conditional`, `distcp`)? When I start to supplement each one of them by complex processing we will loose focus on nodes under test and workfows would become similar to each other.

> Can you add a new fork example (fork2?) with a single consumer that ingests document and person data stores?

Done, yaml file is not generated yet.

**Comment by mkobos** [comment]
> I've slightly improved fs and pig workflows. Yaml files should be regenerated then.

Thanks. 
- `fs` worfklow looks strange from POV of producing and consuming data, namely `init-workingDir` action creates an empty directory and `check-empty-dir` consumes it by verifying that it's empty. But maybe that's the most realistic producer-consumer case related to `fs` that we can get?
- Since you haven't introduced any changes to `conditional` and `distcp`, I guess the present form of the worflows is the most realistic producer-consumer scenario that we can get?

> Anyways, shouldn't we keep those workflows compact (now I am thinking of conditional, distcp)? When I start to supplement each one of them by complex processing we will loose focus on nodes under test and workfows would become similar to each other.

I don't want to have "complex" processing but real-life-like data processing producer-consumer scenarios. This way the data data flow analysis method has non-trivial scenarios to work on.

> >    Can you add a new fork example (fork2?) with a single consumer that ingests document and person data stores?
> 
> Done, yaml file is not generated yet.

Ok.

**Comment by mkobos** [comment]
BTW, I re-generated YAML files for the tests. The tests pass correctly now.

**Comment by marekhorst** [comment]
> fs worfklow looks strange from POV of producing and consuming data, namely init-workingDir action creates an empty directory and check-empty-dir consumes it by verifying that it's empty. But maybe that's the most realistic producer-consumer case related to fs that we can get?

Yeah, I realize it is far from realistic use case but shouldn't it be enough in terms of the action flow? We  could rename `EmptyDirChecker` to be more sophisticated than the current name suggests...

> Since you haven't introduced any changes to conditional and distcp, I guess the present form of the worflows is the most realistic producer-consumer scenario that we can get?

I was trying to find both easy (time-wise) and complex enough scenarios. If complexity is not enough we could always think of something better but let's not forget about time factor. 

I am not sure we need to follow producer-consumer scenario here since those examples could follow different pattern than the one used in integration tests. E.g. why would we need `producer` in `distcp` example? `conditional` example also covers core functionality and adding producer wouldn't bring much to the table unless in the next step we wan't to execute those workflows.

Btw, how do reply to comments with attaching quoted text? I just realized this can be that easy:
https://storify.com/TheAllBox/reply-with-quoted-text-on-github

**Comment by mkobos** [comment]
> > fs worfklow looks strange from POV of producing and consuming data, namely init-workingDir action creates an empty directory and check-empty-dir consumes it by verifying that it's empty. But maybe that's the most realistic producer-consumer case related to fs that we can get?
> 
> Yeah, I realize it is far from realistic use case but shouldn't it be enough in terms of the action flow? We could rename EmptyDirChecker to be more sophisticated than the current name suggests...

I'm interested more in data flow, not in what is the order of execution of different actions. But this should be fine for now.

> >  Since you haven't introduced any changes to conditional and distcp, I guess the present form of the worflows is the most realistic producer-consumer scenario that we can get?
> 
> I was trying to find both easy (time-wise) and complex enough scenarios. If complexity is not enough we could always think of something better but let's not forget about time factor.
> 
> I am not sure we need to follow producer-consumer scenario here since those examples could follow different pattern than the one used in integration tests. E.g. why would we need producer in distcp example? conditional example also covers core functionality and adding producer wouldn't bring much to the table unless in the next step we wan't to execute those workflows.

Ok.

> Btw, how do reply to comments with attaching quoted text? I just realized this can be that easy:
> https://storify.com/TheAllBox/reply-with-quoted-text-on-github

Cool. It's a pity that it doesn't handle text that is already quoted properly though.

**Comment by marekhorst** [comment]
OK, I guess you can merge it, I don't have any new comments to add.

**Pull request closed without merging**
