### PR TITLE
Closes #1: Initial setup of the Python project

### LINKED ISSUE #1: Initial setup of the Python project

### PR DESCRIPTION
**Pull request by mkobos**

### CODE REVIEW

**Comment by mkobos** [comment]
Please review

**Comment by bolo1729** [comment]
Why aren't you using Python 3?

**Comment by mkobos** [comment]
Interesting idea. I have thought that 2.7 is still a more popular version of Python (since e.g. it is the default version on my system), so I would be less likely for to run into trouble while using it. By trouble I mean lack of compatibility with existing libraries. I had a problem like this a couple years ago when I tried to use `mechanize` library, but it turned out it didn't support Python 3 (and it [still doesn't](http://wwwsearch.sourceforge.net/mechanize/faq.html)).

**Comment by bolo1729** [comment]
I get your point. I also occasionally stumble upon (older) libraries that do not support Python 3. However, I recently started choosing P3 for new projects and it's OK. Over time we'll see less P2 and more P3, so it's prudent to base new projects on the latter.

**Comment by mkobos** [comment]
Fair enough.

**Comment by marekhorst** [comment]
Looks good to me. Should I run it locally to see `Hello World`?

**Comment by marekhorst** [comment]
Sorry, closed by accident.

**Comment by mkobos** [comment]
Ok, thanks. Yes, you can run it locally (first run `make install` and then `vipe.py` or `make install-user` and then `~/.local/bin/vipe.py`).

**Pull request closed without merging**
